
export enum TransactionTypeEnum {
  INCOME = 'INCOME',
  INCOME_TAX = 'INCOME_TAX',
  INVEST = 'INVEST',
  SAVINGS = 'SAVINGS',
  HEALTH = 'HEALTH',
  COLLEGE_WORK = 'COLLEGE_WORK',
  CAR = 'CAR',
  GAS = 'GAS',
  GROCERY = 'GROCERY',
  GOVERNMENT = 'GOVERNMENT',
  HOUSING = 'HOUSING',
  UTILITY = 'UTILITY',
  PHONE = 'PHONE',
  PET = 'PET',
  ENTERTAINMENT = 'ENTERTAINMENT',
  MEAL = 'MEAL',
  SHOP = 'SHOP',
  CLOTHES = 'CLOTHES',
  CHARITY = 'CHARITY'
}
