name: Angular CI

on:
  push:
    branches: [ '**' ]          # Run on every push
  pull_request:
    branches: [ main ]          # Run on PRs targeting main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CI: true

    steps:
      # Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20       # Use your Angular project Node version
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build Angular app
      - name: Build Angular app
        run: npm run build       # or 'ng build' if you prefer

      # Run test with coverage
      - name: Run tests with coverage
        run: npm run test -- --code-coverage --watch=false --browsers=ChromeHeadless


